-- PROJETO DIO ECOMMERCE

USE ECOMMERCE;
select * from product;

-- SELECIONA OS PEDIDOS COM STATUS CONFIRMADO
SELECT CONCAT(FNAME, ' ', LNAME) 
	AS CLIENT_NAME, 
	ORDERSTATUS AS ORDER_SITUATION, 
	ORDERDESCRIPTION AS ORDER_DETAILS 
	FROM CLIENTS C, ORDERS O
	WHERE O.ORDERSTATUS = "CONFIRMADO" 
	AND C.IDCLIENT = O.IDORDERCLIENT;
    
-- SELECIONA A QUANTIDADE DE ESTOQUE POR LOCALIZAÇÃO
SELECT SUM(QUANTITY) TOTAL_STORAGE, STORAGELOCATION AS LOCATION_STORAGE
FROM PRODUCT_STORAGE
GROUP BY STORAGELOCATION;

-- SELECIONA OS NOMES DAS EMPRESAS FORNECEDORAS
SELECT SOCIALNAME AS COMPANY_NAME FROM SUPPLIER;

-- SELECIONA QUAIS PRODUTOS E QUAIS AS QUANTIDADES CONSTAM NOS PEDIDOS EM ABERTOS
SELECT idProduct, pname, poQuantity as Sold_Quantity
from PRODUCT
JOIN PRODUCT_ORDER
ON product.idProduct = product_order.idPOproduct;



    










